# Generated by Django 3.0.4 on 2020-04-20 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20200420_1923'),
    ]

    operations = [
    ]
