# Generated by Django 3.0.5 on 2020-04-21 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_auto_20200421_2001'),
    ]

    operations = [
    ]
