# Generated by Django 3.0.5 on 2020-04-21 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_auto_20200421_2057'),
    ]

    operations = [
    ]
