# Generated by Django 3.0.5 on 2020-04-22 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_auto_20200421_2118'),
    ]

    operations = [
    ]
