# Generated by Django 3.0.5 on 2020-04-22 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0006_auto_20200423_0157'),
    ]

    operations = [
    ]
