# Generated by Django 3.0.5 on 2020-04-24 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0007_auto_20200423_0201'),
    ]

    operations = [
    ]
