# Generated by Django 3.0.5 on 2020-04-24 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0008_auto_20200424_1015'),
    ]

    operations = [
    ]
